version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - backend
  back:
    container_name: spring-backend
    build:
      context: spring-boot-VMM
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend
    ports:
      -"8080:8080"
  front:
    container_name: angular-frontend
    build:
      context: angular-VMM
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://127.0.0.1:8080/
      ports:
        - "8081:80" # Map the exposed port 80 on the container to port 8081 on the host machine
    restart: always
    depends_on:
      - back


networks:
  backend: {}
  frontend: {}


